# Generated by Django 3.1 on 2021-02-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rating', '0002_auto_20210212_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.JSONField(max_length=10),
        ),
    ]
